# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.5.27"

package:
  name: python-blockbuster
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/blockbuster/blockbuster-${{ version }}.tar.gz
  sha256: b8e9d988b9b91ba468c94530e219f26a00d3ff616b39ebf3da561a2a3eea9dd4

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - forbiddenfruit >=0.1.4
    - python >=${{ python_min }}

tests:
  - python:
      imports: blockbuster
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - tests/
        - pyproject.toml
    requirements:
      run:
        - pytest-asyncio
        - pytest-cov
        - python ${{ python_min }}.*
        - requests
    script:
      - coverage run --source=blockbuster --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=89

about:
  homepage: https://github.com/cbornet/blockbuster
  license_file: LICENSE
  license: Apache-2.0
  summary: Utility to detect blocking calls in the async event loop

extra:
  recipe-maintainers:
    - bollwyvl
